language: node_js
node_js:
  - 'v16'
  - 'v14'
  - 'v12'
  - 'v10'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm i
script:
  - npm test
  - npm run coverage:ci
